name: Update Badges

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        
    - name: Run script
      run: |
        python3 src/getSteamBadges.py
        
    - name: Push to main branch
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: 'main'
        commit_message: 'Updated Badges'
